### ISSUE TITLE
Remove the compile time value requirement for xTic and yTic?

### ISSUE THREAD

**Issue by kaushalmodi** [benjif/nimetry#4]
Hello,

Can the compile time checks be replaced with run time checks for xTic and yTic?

I would like to use the nimetry based plotting in another application where the xTic and yTic values are provided at run time.

If there is no strong reason to have the compile time checks for just these vars, can they be converted to run time checks?

Thanks for this package!

**Comment by benjif** [comment]
Sounds fine with me, thanks! Merged.
