### ISSUE TITLE
please cut a release :smile:

### ISSUE THREAD

**Issue by disruptek** [benjif/nimetry#6]
I have a requirement against nimetry but I have to specify that requirement by git commit hash because Nimble doesn't know how meet any requirement that isn't tagged, and it seems that no tags exist.

Help a brother out!  :pray:

**Comment by benjif** [comment]
I don't fully understand. Do you want for me to bump the version?

**Comment by disruptek** [comment]
It needs a tag in git.  You can do this via the web interface, or with a command-line call to git like this:

```
git tag -a 0.4.0
```
...followed by a push of the tags, etc.

Foolish as I am, I wrote a little tool to make the particular Nimble process fool-proof: https://github.com/disruptek/bump

**Comment by benjif** [comment]
https://github.com/benjif/nimetry/releases

Done. Is that all?

**Comment by disruptek** [comment]
Perfect, thank you!
